### ISSUE TITLE
Support relative urls

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash-proxy-client-js#94] opened 2022-07-19 12:41 UTC
### Describe the feature request

Proxy client JS should support relative URLS. 

For example, `/features/proxy` should be a valid URL, and it should rely on the browser behaviour to automatically proxy that through the current origin.

**Comment by Tymek** [comment] 2022-07-21 07:27
Duplicate of https://github.com/Unleash/unleash-proxy-client-js/issues/59
Thank you for bringing it to our attention. We will prioritize it 👍🏻

**Closed by Tymek** 2022-07-21 07:27 UTC
Labels: duplicate, enhancement
